# Generated by Django 4.0.4 on 2022-05-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField(null=True)),
                ('expenses', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
