# Generated by Django 4.0.4 on 2022-05-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finlit', '0002_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='salary',
            new_name='income',
        ),
    ]
