# Generated by Django 4.0.4 on 2022-05-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlit', '0003_rename_salary_profile_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='income',
        ),
        migrations.AddField(
            model_name='profile',
            name='desciption',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('ACTIVE', 'Active'), ('PASSIVE', 'Passive')], default='ACTIVE', max_length=10)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('profile', models.ManyToManyField(related_name='income', to='finlit.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses_type', models.CharField(choices=[('BASE', 'Base Expenses'), ('Luxury', 'Luxury Expenses')], default='BASE', max_length=10)),
                ('debt', models.PositiveIntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('profile', models.ManyToManyField(related_name='expenses', to='finlit.profile')),
            ],
        ),
    ]
